common: fix building image.c
Wrap image_decomp() and all dependent functions with
!ifdef(USE_HOSTCC) macro, as this function isn't used by
any tool from /tools.

Without this it leads to compilation issues (because of
CONFIG_LZMA from newly added #include <generated/autoconf.h>
statement, which pulls all these definitions):

In file included from tools/common/image.c:1:0:
./tools/../common/image.c: In function ‘image_decomp’:
./tools/../common/image.c:428:9: warning: implicit declaration of function
‘gunzip’; did you mean ‘munmap’? [-Wimplicit-function-declaration]
   ret = gunzip(load_buf, unc_len, image_buf, &image_len);
         ^~~~~~
         munmap
./tools/../common/image.c:450:3: error: unknown type name ‘SizeT’;
did you mean ‘size_t’?
   SizeT lzma_len = unc_len;
   ^~~~~
   size_t
./tools/../common/image.c:452:9: warning: implicit declaration of function
‘lzmaBuffToBuffDecompress’ [-Wimplicit-function-declaration]
   ret = lzmaBuffToBuffDecompress(load_buf, &lzma_len,
         ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.host:114: recipe for target 'tools/common/image.o' failed

Fixes: 2aa7f0fa51 ("habv4: tools: Avoid hardcoded CSF size for SPL target")
Signed-off-by: Igor Opaniuk <igor.opaniuk@toradex.com>